### PR TITLE
Improve color contrast for concept badge #31

### PR DESCRIPTION
**Pull request by polynoman**
This is a proposal to fix issue #31 . I changed the text color to black and reduced the shadow via the opacity setting to make it clearer.

### CODE REVIEW

**Comment by jantman** [comment]
@polynoman Thanks for this. Once there seems to be consensus between yourself and @drkrynstrng in #31 I'm good with this.

Please note, though, that the badge files shouldn't be directly updated. There's some information in the README ( https://github.com/jantman/repostatus.org#contributing ) but the gist is the badges come from shields.io and are generated by a Fabfile... please also note that older badges are versioned and do _not_ get updated. The color change will only take effect for people who are using ``latest`` or the upcoming release.

**Comment by polynoman** [comment]
@jantman Alright I reverted my changes and made a new version for the badges with better contrast. Please take a look if everything is alright now.

**Comment by polynoman** [comment]
And please label my PR with 'hacktoberfest-accepted', if it gets merged! @jantman

**Comment by jantman** [comment]
Thanks for this work and apologies for taking so long to get to it, but the badges need to be generated according to the instructions in the README.

I've done that in #35

**Pull request closed without merging**
